index:
    path: /
    controller: App\Controller\MainPageController::index
redirect_index:
    path: /{hash}
    controller: App\Controller\RedirectController::index
_errors:
    resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
    prefix:   /_error